# Prefix auf Ctrl+A (ergonomischer als Ctrl+B)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Maus aktivieren
set -g mouse on

# Fenster mit intuitiveren Keys splitten
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Vi-Mode
set -g mode-keys vi

# Schönere Farben
set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
