# ─────────────────────────────────────────────
#  SHELL
# ─────────────────────────────────────────────
shell /bin/zsh

# ─────────────────────────────────────────────
#  FONT
# ─────────────────────────────────────────────
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
font_size        14.0